### ISSUE TITLE
add support for vwo revenue tracking

### ISSUE THREAD

**Issue by ndhoule** [segment-integrations/analytics.js-integration-visual-website-optimizer#1]
_From @DirtyAnalytics on May 22, 2014 18:53_

http://visualwebsiteoptimizer.com/knowledge/how-add-revenue-tracking-tests/

_Copied from original issue: segmentio/analytics.js-integrations#160_

**Comment by hankim813** [comment]
this is supported here https://github.com/segment-integrations/analytics.js-integration-visual-website-optimizer/blob/master/lib/index.js#L61
